import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Notes Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-cover bg-center`}
        style={{
          backgroundImage: "url('/bg_1.png')",
          backgroundAttachment: "fixed",
        }}
      >
        <div className="fixed inset-0 bg-black/20 backdrop-blur-sm z-0 pointer-events-none" />
        <Header />
        <main> {children} </main>
        <Footer />
      </body>
    </html>
  );
}
