// Import Next.js metadata type
import type { Metadata } from "next";
// Import Google fonts
import { Geist, Geist_Mono } from "next/font/google";
// Import global styles
import "./globals.css";
// Import header and footer components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Setup Geist Sans font with CSS variable
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Setup Geist Mono font with CSS variable
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the app (used by Next.js)
export const metadata: Metadata = {
  title: "Notes Web App",
  description: "Generated by create next app",
  openGraph: {
    title: "Notes Web App",
    description: "Built with Next.js, Tailwind, TypeScript, shadcn/ui",
    url: "https://Note-app.de",
    siteName: "Notes Web App",
    images: [
      {
        url: "https://localhost:3001/Notes_App_Titel_Picture.png",
        width: 1200,
        height: 630,
        alt: "Notes Web App Preview",
      },
    ],
    locale: "de_DE",
    type: "website",
  },
};

// Root layout component for the entire app
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Main app body with background image and fonts */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-cover bg-center`}
        style={{
          backgroundImage: "url('/bg_1.png')",
          backgroundAttachment: "fixed",
        }}
      >
        {/* Overlay for darkening and blur effect */}
        <div className="fixed inset-0 bg-black/20 backdrop-blur-sm z-0 pointer-events-none" />
        {/* App header */}
        <Header />
        {/* Main content area */}
        <main> {children} </main>
        {/* App footer */}
        <Footer />
      </body>
    </html>
  );
}
